import os
from typing import Literal

class PulseOnError(RuntimeError): ...
class MetricQueueFullError(PulseOnError): ...
class MetricWriterFailedError(PulseOnError): ...
class MetricDrainTimeoutError(PulseOnError): ...
class MetricFlushError(PulseOnError): ...
class MetricFlushTimeoutError(PulseOnError): ...
class RunClosedError(PulseOnError): ...
class ClientClosedError(PulseOnError): ...
class InvalidRunStateError(PulseOnError): ...
class RunAlreadyExistsError(PulseOnError): ...
class RunAlreadyActiveError(PulseOnError): ...
class InvalidConfigurationError(PulseOnError): ...
class StorageError(PulseOnError): ...

class Diagnostics:
    @property
    def pending_reports(self) -> int: ...
    @property
    def queue_full_errors(self) -> int: ...
    @property
    def persisted_reports(self) -> int: ...
    @property
    def writer_state(self) -> str: ...
    @property
    def last_write_error(self) -> str | None: ...
    @property
    def last_flush_run_id(self) -> str | None: ...
    @property
    def last_flush_status(self) -> str: ...
    @property
    def last_flush_error(self) -> str | None: ...

class MetricPoint:
    run_id: str
    metric_key: str
    step: int
    timestamp: str
    value_f64: float
    ingested_at: str

class MetricSummary:
    run_id: str
    metric_key: str
    effective_count: int
    last_step: int
    last_value_f64: float
    min_value_f64: float
    max_value_f64: float

class Project:
    project_id: str
    name: str
    created_at: str

class Run:
    run_id: str
    project_id: str
    name: str
    status: str
    created_at: str
    started_at: str
    finished_at: str | None
    def log(self, key: str, step: int, value: float, /) -> None: ...

class Client:
    def create_project(
        self, name: str, project_id: str | None = None
    ) -> Project: ...
    def get_project(self, project_id: str) -> Project: ...
    def list_projects(self) -> list[Project]: ...
    def create_run(
        self, project_id: str, name: str, run_id: str | None = None
    ) -> Run: ...
    def get_run(self, run_id: str) -> Run: ...
    def resume_run(self, run_id: str) -> Run: ...
    def list_runs(
        self,
        project_id: str,
        *,
        status: Literal["running", "finished", "failed"] | None = None,
        limit: int | None = None,
        offset: int = 0,
    ) -> list[Run]: ...
    def list_orphan_runs(self, project_id: str | None = None) -> list[Run]: ...
    def finish_run(self, run_id: str, timeout: float | None = None) -> Run: ...
    def fail_run(self, run_id: str, timeout: float | None = None) -> Run: ...
    def flush_run_data(self, run_id: str, timeout: float | None = None) -> None: ...
    def shutdown(self, timeout: float | None = None) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(
        self, exc_type: object, exc_value: object, traceback: object
    ) -> bool: ...
    def diagnostics(self) -> Diagnostics: ...
    def query_metric(
        self,
        run_id: str,
        metric_key: str,
        start_step: int | None = None,
        end_step: int | None = None,
        max_points: int | None = None,
    ) -> list[MetricPoint]: ...
    def query_metric_summaries(
        self, run_ids: list[str], metric_key: str
    ) -> list[MetricSummary]: ...
    def list_metrics(self, run_id: str) -> list[MetricSummary]: ...

def init(
    path: str | os.PathLike[str] = ".",
    *,
    data_path: str | os.PathLike[str] | None = None,
    catalog_backend: Literal["duckdb", "sqlite"] = "duckdb",
    catalog_path: str | os.PathLike[str] | None = None,
    metric_queue_capacity: int = 65536,
    s3_endpoint: str | None = None,
    s3_access_key_id: str | None = None,
    s3_secret_access_key: str | None = None,
    s3_session_token: str | None = None,
    s3_region: str | None = None,
    s3_path_style: bool | None = None,
    s3_use_ssl: bool | None = None,
) -> Client: ...
